### ISSUE TITLE
Updating A Repository 

### ISSUE THREAD

**Issue by Dodoodilee** [Psycokwet/Ask-me-anything#2]
Good Morning , 

Usually when i have to update my repository i have to open a youtube video and then i follow the steps specified in the video to update my repository . several times i have failed because on vscode i forget to save the updated file and then it dosent gets updated on github ! 

https://www.youtube.com/watch?v=vbQ2bYHxxEA&list=PL_D2eIxNtrEWbIBQ3quhJOlaif729TqBM&index=11

this is the video i watch to create or modify / update a repository ! 

i believe there must be an easier way to do this as well . 

i would like to know the way how professionals do it ! 

how would you update a repository ? and create one ! ill appreciate if you could write each steps one by one and then i will use them to test ! 

Regards,
Dorian D.

**Comment by Psycokwet** [comment]
Hello :) 
So first of all, I think you should take notes on what you have to do instead of watching this video as often, it would be easier to just read your notes.
Basically to update a repository you need only those : 
Save your files. Check that the little 
![Screenshot 2024-02-26 at 07 33 12](https://github.com/Psycokwet/Ask-me-anything/assets/14911120/eb167caf-12d4-4bef-b70b-6fbd0ca3bf13)
is absent from the tab where you filename is written.
Then proceed with following commands

```git status```
shows you every files you have that are modified and not yet followed by github to be saved in your next commit to send in your distant repository

```git add [FILEPATH/FILENAME]```
where [FILEPATH/FILENAME] is the actual file you want to put in your distant repository with the relative or absolute path so that github can find it.
You can copy paste the filepath to a file directly from what git status command gives you as output. ctrl+shift+c to copy from terminal, ctrl + shift + v to paste in terminal.

```commit -m"Clever message explaining what this commit encompass as changes for the distant repository"```
This will save locally your changes with git. Locally only.
Then to push your locally saved commit to the distant repository you do

```git push```

And you are all set :) Let me know if a step described here is not clear enough for you :)

**Comment by Psycokwet** [comment]
As for the question "How professionals do it" the answer depends on who you ask that to. Most developer will use the aforementioned commands, while I prefer to use something that gives me a visual on what I do. I personally use [this software](https://www.gitkraken.com/) It basically does those commands, but allows me for a visual check on what I do. Once you understand the 4 commands I describe up there, you can try out gitkraken, not before. You need to understand what lies below gitkraken as well.

Also, most of the repository you created are private, and git kraken free plan only allows you to work on public repository, so if you want to use it, you will have to do public repository instead (you can change the visibility of your current repo to public for that if needed). There is a lot of other visual git software, but I'm not familiar nor I know much what the others are as I'm pretty satisfied with gitkraken, but feel free to search online for a nice fully free one if you want !

**Comment by Psycokwet** [comment]
PS : You can have a visual of what you do with git commands as well, but I never cared to learn those commands, but I know my colleagues uses them

**Comment by Dodoodilee** [comment]
How would you update a repository ? lets suppose you have a file you currently modified and its already created in github as repository and you made some changes to the data of the file on vscode now how would you update it and its repository on github . 

please specify in steps , one by one how would you do it as you explained how to create a repository earlier 

Thankyou !

**Comment by Dodoodilee** [comment]
i believe you did made me install docker and several others softwares on my pc which also included gitkraken but you never taught me how to use gitkraken though . its installed on my computer . i will appreciate if we can colloborate on this and go through it .

Thankyou

**Comment by Psycokwet** [comment]
Commenting here to try to remember to make you a video showing you what I do exactly step by step. If I don't before sunday, don't hesitate to ping me back

**Comment by Dodoodilee** [comment]
great , thanks :D

**Comment by Psycokwet** [comment]
https://www.loom.com/share/e117a262f8b1454e96861e785466e219
https://www.loom.com/share/5818a4f632274393a1ac20695e791ab8

Can you see those ?
